### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by vbaranov** [oraclesorg/treasury#1]
Truffle tests dont work.

>viktors-MacBook-Pro:treasury viktor$ truffle version
>Truffle v4.0.0 (core: 4.0.0)
>Solidity v0.4.18 (solc-js)

```
  Contract: Treasury [all features]
    ✓ Decimals attribute (41ms)
    ✓ Token address before initialization
    ✓ Exchange rate before initialization
    1) Initialization
    > No events were emitted
    2) Initialization could be run only once
    > No events were emitted
    3) tokenDepositEvent
    > No events were emitted
    4) tokenDepositEvent fails from non-token address
    > No events were emitted
    5) tokenDepositEvent generates Exchange event
    > No events were emitted
    6) getEtherBalance
    > No events were emitted


  3 passing (973ms)
  6 failing

  1) Contract: Treasury [all features] Initialization:
     Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the senders account only has: 98609834300000000000
    at runCall (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69347:10)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36)
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  2) Contract: Treasury [all features] Initialization could be run only once:
     Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the senders account only has: 98551261800000000000
    at runCall (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69347:10)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36)
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  3) Contract: Treasury [all features] tokenDepositEvent:
     Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the senders account only has: 98492689300000000000
    at runCall (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69347:10)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36)
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  4) Contract: Treasury [all features] tokenDepositEvent fails from non-token address:
     Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the senders account only has: 98434116800000000000
    at runCall (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69347:10)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36)
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  5) Contract: Treasury [all features] tokenDepositEvent generates Exchange event:
     Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the senders account only has: 98375544300000000000
    at runCall (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69347:10)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36)
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  6) Contract: Treasury [all features] getEtherBalance:
     Error: Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the senders account only has: 98316971800000000000
    at runCall (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:69347:10)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11327:24
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8420:17)
    at iterateeCallback (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8405:17)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8380:16
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11332:13
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64434:16
    at replenish (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64381:25)
    at /Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64390:9
    at eachLimit (/Users/viktor/.npm-packages/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:64314:36)
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
```

**Comment by vbaranov** [comment]
Tests still don't work for me nor with testrpc neither with Kovan Parity. 
Current log:
```
  Contract: Treasury [all features]
    1) setTreasury fails for non-owner

    Events emitted during test:
    ---------------------------


    ---------------------------
    ✓ setTreasury sets treasury contract (5278ms)

  Contract: Treasury [all features]
    ✓ Decimals attribute (186ms)
    ✓ Token address before initialization
    ✓ Exchange rate before initialization
    2) Initialization

    Events emitted during test:
    ---------------------------


    ---------------------------
    3) Initialization could be run only once
    > No events were emitted
    4) tokenDepositEvent
    > No events were emitted
    5) tokenDepositEvent fails from non-token address

    Events emitted during test:
    ---------------------------


    ---------------------------
    6) tokenDepositEvent generates Exchange event
    > No events were emitted
    7) getEtherBalance
    > No events were emitted
    8) tokenDepositEvent [from real token]

    Events emitted during test:
    ---------------------------


    ---------------------------
    9) tokenDepositEvent is not called for transfer to non-treasury recipient

    Events emitted during test:
    ---------------------------


    ---------------------------


  4 passing (4m)
  9 failing

  1) Contract: Treasury [all features] setTreasury fails for non-owner:

      AssertionError: expected promise to be rejected with an error including 'invalid opcode' but got 'invalid address'
      + expected - actual

      -invalid address
      +invalid opcode
      
  

  2) Contract: Treasury [all features] Initialization:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 9421062901129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  3) Contract: Treasury [all features] Initialization could be run only once:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 9214492901129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  4) Contract: Treasury [all features] tokenDepositEvent:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 9007922901129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  5) Contract: Treasury [all features] tokenDepositEvent fails from non-token address:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 8801352901129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  6) Contract: Treasury [all features] tokenDepositEvent generates Exchange event:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 8594782901129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  7) Contract: Treasury [all features] getEtherBalance:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 8388212901129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  8) Contract: Treasury [all features] tokenDepositEvent [from real token]:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 8177277801129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

  9) Contract: Treasury [all features] tokenDepositEvent is not called for transfer to non-treasury recipient:
     Error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100200000000000000000 and got: 7966342701129934320.
      at Object.InvalidResponse (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:331150:36
      at /Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/Users/viktor/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
```

**Comment by lorien** [comment]
Testrpc через make запускаешь?   Посмотри в Makefile команду testrpc
